version: '3.7'

services:
  mariadb:
    image: mariadb_img
    init: true
    networks: 
      - inception
    restart: always
    build:
      context: requirements/mariadb
      args:
        DB_USR_NAME: ${DB_USR_NAME}
        DB_USR_PSWRD: ${DB_USR_PSWRD}
        DB_ROOT_PSWRD: ${DB_ROOT_PSWRD}
        DB_NAME: ${DB_NAME}
    env_file: 
      - .env
    # volumes:
    #   - /goinfre/lboudjem/mariadb:/var/lib/mysql
    container_name: mydatabase

  wordpress:
    image: wordpress_img
    init: true
    networks:
      - inception
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    expose:
      - "9000"
    volumes:
      - wordpress_vol:/var/www/wordpress
    restart: always
    container_name: mywordpress
  
  nginx:
    image: nginx_img
    init: true
    networks:
      - inception
    build: requirements/nginx
    ports:
      - "8443:443"
      # - "8080:80"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/wordpress
    container_name: mynginx

volumes:
#   mariadb_vol:
#     driver: local
#     driver_opts:
#       type: 'none' 
#       o: 'bind'	
#       device: '/goinfre/lboudjem/mariadb'	
  wordpress_vol:
    driver: local 
    driver_opts:
      type: 'none' 								
      o: 'bind'
      device: '/goinfre/lboudjem/wordpress'

networks:
  inception:
    driver: bridge
    name: inception